#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 30 21:42:42 2019

@author: quynh
"""
import numpy as np
import pandas as pd
from datetime import datetime

data = pd.read_csv('SalesForce_Contact.csv', encoding='latin', low_memory=False)

#General Method to explore the features
def count_value_null(feature, data):
    #print("Feature = ", feature)
    print("Number of records:", len(data[feature].index))
    print("Null Values:", data[feature].isna().sum())
    print("Null Values %:", data[feature].isna().sum()/len(data.index)*100)
    print("Unique Values:", data[feature].nunique())
    print("Top 10 Value Counts:")
    print(data[feature].value_counts().head(10))
    print("\n")
    

count_value_null(Regional_Manager_Approved__c, data)
count_value_null(Hire_Heroes_USA_Confirmed_Hire__c, data)
#
confirmed_hire = data[(data['Hire_Heroes_USA_Confirmed_Hire__c']==1)]
confirmed_hire.shape